### ISSUE TITLE
Orient core team to concepts and documentatin

### ISSUE THREAD

**Issue by davclark** [dlab-berkeley/dlab-berkeley.github.io#3]
- [x] What is a static site?
- [x] [Jekyll Docs](http://jekyllrb.com/)
- [x] Orientation to [the D-Lab's static site](http://dlab-berkeley.github.io) (hosted right here in this repo!)

**Comment by susangrand** [comment]
[ ] this is a check box

**Comment by susangrand** [comment]
- [ ] how about this?
  :collision:
